### ISSUE TITLE
netlink example, glide installation broken

### ISSUE THREAD

**Issue by maq123** [osrg/goplane#27]
I follow this doc to try the demo : https://github.com/osrg/goplane/blob/master/test/netlink/README.md
However after issuing the ```glide install``` I get the following error:

`Failed to set version on github.com/osrg/gobgp to ce12b084250bfd8b8ea86a62c88f43e72b0dae38: Unable to update checked out version`

**Comment by ishidawataru** [comment]
should be fixed now. Please pull and try again.
